# Generated by Django 5.1.1 on 2024-09-19 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FoodFinder", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favoriateCuisine",
                    models.CharField(
                        choices=[
                            ("Italian", "Italian"),
                            ("Chinese", "Chinese"),
                            ("Thai", "Thai"),
                            ("Indian", "Indian"),
                            ("Mexican", "Mexican"),
                            ("American", "American"),
                            ("Greek", "Greek"),
                            ("Korean", "Korean"),
                            ("Japanese", "Japanese"),
                            ("Vietnamese", "Vietnamese"),
                        ],
                        default="American",
                        max_length=15,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
