# Generated by Django 4.2.15 on 2024-09-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FoodFinder", "0002_profile_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("place_id", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="favoriateCuisine",
            new_name="favoriteCuisine",
        ),
    ]
