# Generated by Django 5.1.1 on 2024-09-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FoodFinder", "0003_restaurant_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="restaurant", name="address",),
        migrations.RemoveField(model_name="restaurant", name="created_at",),
        migrations.RemoveField(model_name="restaurant", name="rating",),
        migrations.AddField(
            model_name="restaurant",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
    ]
